apiVersion: v1
kind: ConfigMap
metadata:
  name: helpdesk-app-config
data:
  DATABASE_HOST: postgres
  REDIS_HOST: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helpdesk-frontend-nginx
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helpdesk-database-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS tickets (
        id SERIAL PRIMARY KEY,
        employee_name VARCHAR(100) NOT NULL,
        issue TEXT NOT NULL,
        priority VARCHAR(20) NOT NULL CHECK (
            priority IN ('Low', 'Medium', 'High', 'Critical')
        ),
        status VARCHAR(20) DEFAULT 'Open' CHECK (
            status IN ('Open', 'Assigned', 'In Progress', 'Waiting', 'Resolved', 'Closed')
        ),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
