apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: helpdesk-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy

  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: helpdesk-proxy-config

  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: allowed
